name: Terraform S3 Provisioning

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform S3
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: ap-south-1
      TF_VAR_bucket_name: jayanth-devops-s3-2026-84729
      TF_VAR_environment: dev
      TF_VAR_force_destroy: false

    steps:

      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_aws_region }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 5. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 6. Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      - name: Import Existing Resources
        run: |
          terraform import aws_s3_bucket.project_bucket jayanth-devops-s3-2026-84729 || true
          terraform import aws_ecr_repository.app jayanth-devops-app || true
          terraform import aws_cloudwatch_log_group.ecs /ecs/jayanth-devops || true
          terraform import aws_iam_role.ecs_task_execution jayanth-devops-ecs-execution-role || true
          terraform import aws_vpc.main vpc-0425909ee6d1b525e || true

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
