name: Terraform S3 Provisioning

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform S3
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: ap-south-1
      TF_VAR_bucket_name: jayanth-devops-s3-2026-84729
      TF_VAR_environment: dev
      TF_VAR_force_destroy: false
      TF_VAR_container_image: 746931977188.dkr.ecr.ap-south-1.amazonaws.com/jayanth-devops-app:latest

    steps:

      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_aws_region }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -recursive

      # 5. Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # 6. Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      - name: Import Existing Resources
        run: |
         terraform import aws_s3_bucket.project_bucket jayanth-devops-s3-2026-84729 || true
         terraform import aws_ecr_repository.app jayanth-devops-app || true
         terraform import aws_cloudwatch_log_group.ecs /ecs/jayanth-devops || true

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # 9. Login to GitHub Container Registry
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ secrets.GHCR_USERNAME }}" \
            --password-stdin

      # 10. Pull Nexvion image from GHCR
      - name: Pull Nexvion Image
        run: |
          docker pull ghcr.io/jayanth125/nexvion:latest

      # 11. Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 12. Tag and Push Image to ECR
      - name: Push Nexvion Image to ECR
        env:
          ECR_REGISTRY: 746931977188.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: jayanth-devops-app
        run: |
          docker tag ghcr.io/jayanth125/nexvion:latest \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest

          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # 13. Force ECS Deployment
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster jayanth-devops-cluster \
            --service jayanth-devops-service \
            --force-new-deployment \
            --region ap-south-1

      # 14. Verify ECS deployment
      - name: Verify ECS Service
        run: |
          aws ecs wait services-stable \
            --cluster jayanth-devops-cluster \
            --services jayanth-devops-service \
            --region ap-south-1

          aws ecs describe-services \
            --cluster jayanth-devops-cluster \
            --services jayanth-devops-service \
            --region ap-south-1 \
            --query 'services[0].{Status:status,Running:runningCount,Desired:desiredCount}'
